language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

env:
  matrix:
    - COMPOSER_OPTIONS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cp .env.example .env

install:
  - travis_retry composer update ${COMPOSER_OPTIONS} --prefer-source

script:
  - phpunit